<?php
	/********************************************************************
	 * Photo Album v1.0
	 * Written by: Robbie Hott
	 * http://www.robbiehott.com
	 * (c) 2005
	 *
	 * This code may be shared and updated for free, as long as you do not
	 * claim it as your own and leave this comment in tact.
	 *
	 * DO NOT EDIT THIS FILE
	 ********************************************************************/
	 
function LoadJpeg($imgname) 
{
   $im = @imagecreatefromjpeg($imgname); /* Attempt to open */
   if (!$im) { /* See if it failed */
       $im  = imagecreate(150, 30); /* Create a blank image */
       $bgc = imagecolorallocate($im, 255, 255, 255);
       $tc  = imagecolorallocate($im, 0, 0, 0);
       imagefilledrectangle($im, 0, 0, 150, 30, $bgc);
       /* Output an errmsg */
       imagestring($im, 1, 5, 5, "Error loading $imgname", $tc);
   }
   return $im;
}

function LoadJpegThumbnail($imgname, $maxwidth, $maxheight) 
{
   $im = @imagecreatefromjpeg($imgname); /* Attempt to open */
   if (!$im) { /* See if it failed */
       $im  = imagecreate(150, 30); /* Create a blank image */
       $bgc = imagecolorallocate($im, 255, 255, 255);
       $tc  = imagecolorallocate($im, 0, 0, 0);
       imagefilledrectangle($im, 0, 0, 150, 30, $bgc);
       /* Output an errmsg */
       imagestring($im, 1, 5, 5, "Error loading $imgname", $tc);
       return $im;
   }
   $oldwidth = imagesx($im);
   $oldheight = imagesy($im);

   if ($oldwidth > $oldheight) {
	   $newwidth = $maxwidth;
	   $newheight = ( $maxwidth / $oldwidth ) * $oldheight;
   } else {
	   $newheight = $maxheight;
	   $newwidth = ( $maxheight / $oldheight ) * $oldwidth;
   }

   $resized = imagecreatetruecolor($newwidth, $newheight);
   imagecopyresized($resized, $im, 0, 0, 0, 0, $newwidth, $newheight, $oldwidth, $oldheight);
   return $resized;
}

if ($_GET["type"] == "thumbnail") 
	$imageData = LoadJpegThumbnail($_GET["i"], 100, 100);
else if ($_GET["type"] == "fullsize")
	$imageData = LoadJpegThumbnail($_GET["i"], 500, 500);
else
	$imageData = LoadJpeg($_GET["i"]);

Header( "Content-Type: image/jpeg");

imagejpeg($imageData, '', 100); 

?>
