<?php
	/********************************************************************
	 * Photo Album v1.0
	 * Written by: Robbie Hott
	 * http://www.robbiehott.com
	 * (c) 2005
	 *
	 * This code may be shared and updated for free, as long as you do not
	 * claim it as your own and leave this comment in tact.
	 *
	 * DO NOT EDIT THIS FILE
	 ********************************************************************/
	include("album.inc");
	
	
	// User Defined Vars
	/********************************************************************
	 * Change the location in the quotes to the location of your image
	 * folders.  For example, the definition below says my pictures and
	 * folders are in 'thiscurrentfolder/images/photos'.
	 ********************************************************************/
	$location = "images/photos"; // change to the location of your folders


	// Definitions
	$album = $_GET['album'];
	$image = $_GET['image'];
	
?>
<html>
<body>
<h1>Photo Gallery</h1>
<?php
	/*********************************************************************
	 * DO NOT EDIT BELOW THIS LINE
	 *********************************************************************/
	if($album == "") {
		// print the current albums
		echo "<p>current albums :</p>
			<div class=\"photoalbum\">";
		print_albums($location, -1);
		echo "</div>";
	} else if ($image == "") {
		// print the images in the album
		echo "<p><a href=\"?\">current albums</a> :: $album</p>
			<div class=\"photoalbum\">";
		print_album_contents($location, $album);
		echo "</div>";
	} else { 
		// print the fullsize image
		echo "<p><a href=\"?album=$album\">$album</a> :: $image</p>
			<div class=\"photoalbum\">
			<center><img src='image.php?i=$location/$album/$image&type=fullsize' border='0' alt=\"$image\"><br/>
			<p><a href=\"$location/$album/$image\">get the full size image</a></p><br/><br/></center>
		      </div>";
	}
	/*********************************************************************
	 * DO NOT EDIT ABOVE THIS LINE
	 *********************************************************************/
?>
</body>
</html>
